SECRET_TOKEN:
DEVISE_SECRET:
DEFAULT_EMAIL_FROM:               test@test.com
DOMAIN_NAME:                      fictionist.dev
ADMIN_EMAIL:                      test@test.com
ADMIN_PASSWORD:                   '12345678'
ADMIN_NAME:                       test admin

TWITTER_KEY:
TWITTER_SECRET:
FACEBOOK_KEY:
FACEBOOK_SECRET:

S3_BUCKET_NAME:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
